### ISSUE TITLE
crosshatch/blueline R Android 11

### ISSUE THREAD

**Issue by chirayudesai** [AOSPAlliance/android-prepare-vendor#32]
- [x] Verified Boot
- [x] Wi-Fi
- [x] Bluetooth
- [x] Camera
- [x] Sound
- [x] Biometrics - fingerprint / face unlock
- [x] Flashlight / torch
- [x] GPS
- [x] Hotspot
- [x] NFC
- [x] Calls
- [x] Text Messages / SMS
- [x] Mobile data
- [x] VoLTE
- [x] Wi-Fi Calling
- [x] Quickly go through logs to make sure there's no obvious crashes / missing libs / etc

**Comment by chirayudesai** [comment]
Also mention:
APV commit, and OS tested with (AOSP/a fork/etc)

**Comment by dan-v** [comment]
Verified on crosshatch with RattlesnakeOS build using APV commit 8868b90c6b5deeb814cdffd6eb9dfcba93b68422. Also validated OTA updates through updater app (with additional selinux rules). While there is nothing spamming super frequently in logcat, it is definitely not completely clean.

<details>
  <summary>Logcat</summary>
  
```
09-18 20:27:26.509   957   957 E libpixelpowerstats: getResults: wlan is unloaded
09-18 20:27:28.070   952   952 W healthd : battery l=97 v=4386 t=27.6 h=2 st=2 c=-472187 fc=3003000 cc=301 chg=a
09-18 20:27:46.590  2563  3513 E Dialer  : ImapHelper - Messaging Exception
09-18 20:27:46.590  2563  3513 E Dialer  : com.android.voicemail.impl.mail.MessagingException: java.net.SocketTimeoutException: failed to connect to ue.mstore.msg.t-mobile.com/208.54.144.145 (port 143) from /192.0.0.4 (port 38092) after 10000ms
09-18 20:27:46.590  2563  3513 E Dialer  :    at com.android.voicemail.impl.mail.MailTransport.open(MailTransport.java:33)
09-18 20:27:46.590  2563  3513 E Dialer  :    at com.android.voicemail.impl.mail.store.ImapConnection.sendCommand(ImapConnection.java:4)
09-18 20:27:46.590  2563  3513 E Dialer  :    at com.android.voicemail.impl.mail.store.ImapConnection.executeSimpleCommand(ImapConnection.java:1)
09-18 20:27:46.590  2563  3513 E Dialer  :    at com.android.voicemail.impl.mail.store.ImapFolder.doSelect(ImapFolder.java:3)
09-18 20:27:46.590  2563  3513 E Dialer  :    at com.android.voicemail.impl.mail.store.ImapFolder.open(ImapFolder.java:5)
09-18 20:27:46.590  2563  3513 E Dialer  :    at com.android.voicemail.impl.imap.ImapHelper.openImapFolder(ImapHelper.java:3)
09-18 20:27:46.590  2563  3513 E Dialer  :    at com.android.voicemail.impl.imap.ImapHelper.fetchAllVoicemails(ImapHelper.java:2)
09-18 20:27:46.590  2563  3513 E Dialer  :    at com.android.voicemail.impl.sync.OmtpVvmSyncService.syncAll(OmtpVvmSyncService.java:1)
09-18 20:27:46.590  2563  3513 E Dialer  :    at com.android.voicemail.impl.sync.OmtpVvmSyncService.doSync(OmtpVvmSyncService.java:2)
09-18 20:27:46.590  2563  3513 E Dialer  :    at com.android.voicemail.impl.sync.OmtpVvmSyncService.sync(OmtpVvmSyncService.java:15)
09-18 20:27:46.590  2563  3513 E Dialer  :    at com.android.voicemail.impl.sync.SyncTask.onExecuteInBackgroundThread(SyncTask.java:2)
09-18 20:27:46.590  2563  3513 E Dialer  :    at com.android.voicemail.impl.scheduling.TaskExecutor$WorkerThreadHandler.handleMessage(TaskExecutor.java:4)
09-18 20:27:46.590  2563  3513 E Dialer  :    at android.os.Handler.dispatchMessage(Handler.java:106)
09-18 20:27:46.590  2563  3513 E Dialer  :    at android.os.Looper.loop(Looper.java:223)
09-18 20:27:46.590  2563  3513 E Dialer  :    at android.os.HandlerThread.run(HandlerThread.java:67)
09-18 20:27:46.642  2563  3513 E Dialer  : OmtpVvmSyncService - syncAll: query failed
09-18 20:28:06.893  2563  3513 E Dialer  : ImapConnection - Error while logging out:com.android.voicemail.impl.mail.MessagingException: java.net.SocketTimeoutException: failed to connect to ue.mstore.msg.t-mobile.com/208.54.144.145 (port 143) from /192.0.0.4 (port 38096) after 10000ms
09-18 20:28:09.130   952   952 W healthd : battery l=98 v=4386 t=27.4 h=2 st=2 c=-455625 fc=3003000 cc=301 chg=a
09-18 20:28:12.019   957   957 E libpixelpowerstats: getResults: wlan is unloaded
09-18 20:28:28.078   952   952 W healthd : battery l=98 v=4386 t=27.3 h=2 st=2 c=-440937 fc=3003000 cc=301 chg=a
09-18 20:28:32.385  2563  3513 E Dialer  : ImapHelper - Messaging Exception
09-18 20:28:32.385  2563  3513 E Dialer  : com.android.voicemail.impl.mail.MessagingException: java.net.SocketTimeoutException: failed to connect to ue.mstore.msg.t-mobile.com/208.54.144.148 (port 143) from /192.0.0.4 (port 37804) after 10000ms
09-18 20:28:32.385  2563  3513 E Dialer  :    at com.android.voicemail.impl.mail.MailTransport.open(MailTransport.java:33)
09-18 20:28:32.385  2563  3513 E Dialer  :    at com.android.voicemail.impl.mail.store.ImapConnection.sendCommand(ImapConnection.java:4)
09-18 20:28:32.385  2563  3513 E Dialer  :    at com.android.voicemail.impl.mail.store.ImapConnection.executeSimpleCommand(ImapConnection.java:1)
09-18 20:28:32.385  2563  3513 E Dialer  :    at com.android.voicemail.impl.mail.store.ImapFolder.doSelect(ImapFolder.java:3)
09-18 20:28:32.385  2563  3513 E Dialer  :    at com.android.voicemail.impl.mail.store.ImapFolder.open(ImapFolder.java:5)
09-18 20:28:32.385  2563  3513 E Dialer  :    at com.android.voicemail.impl.imap.ImapHelper.openImapFolder(ImapHelper.java:3)
09-18 20:28:32.385  2563  3513 E Dialer  :    at com.android.voicemail.impl.imap.ImapHelper.fetchAllVoicemails(ImapHelper.java:2)
09-18 20:28:32.385  2563  3513 E Dialer  :    at com.android.voicemail.impl.sync.OmtpVvmSyncService.syncAll(OmtpVvmSyncService.java:1)
09-18 20:28:32.385  2563  3513 E Dialer  :    at com.android.voicemail.impl.sync.OmtpVvmSyncService.doSync(OmtpVvmSyncService.java:2)
09-18 20:28:32.385  2563  3513 E Dialer  :    at com.android.voicemail.impl.sync.OmtpVvmSyncService.sync(OmtpVvmSyncService.java:15)
09-18 20:28:32.385  2563  3513 E Dialer  :    at com.android.voicemail.impl.sync.SyncTask.onExecuteInBackgroundThread(SyncTask.java:2)
09-18 20:28:32.385  2563  3513 E Dialer  :    at com.android.voicemail.impl.scheduling.TaskExecutor$WorkerThreadHandler.handleMessage(TaskExecutor.java:4)
09-18 20:28:32.385  2563  3513 E Dialer  :    at android.os.Handler.dispatchMessage(Handler.java:106)
09-18 20:28:32.385  2563  3513 E Dialer  :    at android.os.Looper.loop(Looper.java:223)
09-18 20:28:32.385  2563  3513 E Dialer  :    at android.os.HandlerThread.run(HandlerThread.java:67)
09-18 20:28:32.438  2563  3513 E Dialer  : OmtpVvmSyncService - syncAll: query failed
09-18 20:28:45.215  1485  1890 E WifiClientModeImpl: getWifiLinkLayerStats called without an interface
09-18 20:28:45.229  3093  3093 E i2c_geni 88c000.i2c: i2c error :-107
09-18 20:28:45.256  1939  1939 W View    : requestLayout() improperly called by com.android.keyguard.CarrierText{cf99ae9 V.ED..... ......ID 56,0-462,172 #7f0a025c app:id/keyguard_carrier_text} during layout: running second layout pass
09-18 20:28:45.364   711   711 E i2c_geni 888000.i2c: GSI QN err:0x0, status:0x3ea, err:2
09-18 20:28:45.364   711   711 E i2c_geni 888000.i2c: GSI QN err:0x0, status:0x3ea, err:2
09-18 20:28:52.612  2563  3513 E Dialer  : ImapConnection - Error while logging out:com.android.voicemail.impl.mail.MessagingException: java.net.SocketTimeoutException: failed to connect to ue.mstore.msg.t-mobile.com/208.54.144.148 (port 143) from /192.0.0.4 (port 37808) after 10000ms
09-18 20:28:55.182  1485  1570 E libc    : Access denied finding property "vendor.debug.egl.changepixelformat"
09-18 20:28:55.207  1485  1570 E libc    : Access denied finding property "vendor.debug.egl.swapinterval"
09-18 20:28:55.464  1485  1570 E libc    : Access denied finding property "vendor.debug.egl.swapinterval"
09-18 20:28:55.482  1485  1570 E libc    : Access denied finding property "vendor.debug.egl.swapinterval"
09-18 20:28:55.631  1485  1570 E libc    : Access denied finding property "vendor.debug.egl.swapinterval"
09-18 20:28:55.920  1939  2475 E KeyguardViewMediator: resetStateLocked
09-18 20:28:55.924  1485  1890 E WifiClientModeImpl: getWifiLinkLayerStats called without an interface
09-18 20:28:55.931  1939  1939 W View    : requestLayout() improperly called by com.android.keyguard.CarrierText{cf99ae9 V.ED..... ......ID 56,0-462,172 #7f0a025c app:id/keyguard_carrier_text} during layout: running second layout pass
09-18 20:28:55.956  3093  3093 E i2c_geni 88c000.i2c: i2c error :-107
09-18 20:29:28.070   952   952 W healthd : battery l=98 v=4385 t=27.2 h=2 st=2 c=-434687 fc=3003000 cc=301 chg=a
09-18 20:29:38.640   952   952 W healthd : battery l=99 v=4387 t=27.1 h=2 st=2 c=-425625 fc=3003000 cc=301 chg=a
09-18 20:30:28.076   952   952 W healthd : battery l=99 v=4389 t=26.8 h=2 st=2 c=-417187 fc=3003000 cc=301 chg=a
09-18 20:30:28.083   957   957 E libpixelpowerstats: getResults: wlan is unloaded
09-18 20:30:33.963   952   952 W healthd : battery l=100 v=4388 t=26.7 h=2 st=2 c=-406250 fc=3003000 cc=301 chg=a
09-18 20:30:42.875   952   952 W healthd : battery l=100 v=4387 t=26.7 h=2 st=2 c=-408125 fc=3003000 cc=301 chg=a
09-18 20:30:42.881   957   957 E libpixelpowerstats: getResults: wlan is unloaded
09-18 20:31:28.074   952   952 W healthd : battery l=100 v=4387 t=26.5 h=2 st=2 c=-391562 fc=3003000 cc=301 chg=a
09-18 20:32:28.076   952   952 W healthd : battery l=100 v=4386 t=26.3 h=2 st=2 c=-374375 fc=3003000 cc=301 chg=a
09-18 20:33:22.000  1485  1890 E WifiClientModeImpl: getWifiLinkLayerStats called without an interface
09-18 20:33:22.016  3093  3093 E i2c_geni 88c000.i2c: i2c error :-107
09-18 20:33:22.021   958  1040 E ASH     : @ 610.504: touch gesture: Recovered controller after watchdog in 0 attempts
09-18 20:33:22.021  1939  1939 W View    : requestLayout() improperly called by com.android.keyguard.CarrierText{cf99ae9 V.ED..... ......ID 56,0-462,172 #7f0a025c app:id/keyguard_carrier_text} during layout: running second layout pass
09-18 20:33:22.022   958  1040 W ASH     : @ 610.506: touch gesture: no valid gesture detected
09-18 20:33:22.026   958  1040 W ASH     : @ 610.509: touch gesture: no valid gesture detected
09-18 20:33:22.027   958  1040 W ASH     : @ 610.510: touch gesture: no valid gesture detected
09-18 20:33:28.079   952   952 W healthd : battery l=100 v=4388 t=26.1 h=2 st=2 c=-357187 fc=3003000 cc=301 chg=a
09-18 20:33:31.994  1485  1570 E libc    : Access denied finding property "vendor.debug.egl.changepixelformat"
09-18 20:33:32.020  1485  1570 E libc    : Access denied finding property "vendor.debug.egl.swapinterval"
09-18 20:33:32.233  1485  1570 E libc    : Access denied finding property "vendor.debug.egl.swapinterval"
09-18 20:33:32.250  1485  1570 E libc    : Access denied finding property "vendor.debug.egl.swapinterval"
09-18 20:33:32.451  1485  1570 E libc    : Access denied finding property "vendor.debug.egl.swapinterval"
09-18 20:33:32.740  1939  2059 E KeyguardViewMediator: resetStateLocked
09-18 20:33:32.746  1485  1890 E WifiClientModeImpl: getWifiLinkLayerStats called without an interface
09-18 20:33:32.751  1939  1939 W View    : requestLayout() improperly called by com.android.keyguard.CarrierText{cf99ae9 V.ED..... ......ID 56,0-462,172 #7f0a025c app:id/keyguard_carrier_text} during layout: running second layout pass
09-18 20:33:32.774  3093  3093 E i2c_geni 88c000.i2c: i2c error :-107
09-18 20:34:20.269  1485  1890 E WifiClientModeImpl: getWifiLinkLayerStats called without an interface
09-18 20:34:20.290  1939  1939 W View    : requestLayout() improperly called by com.android.keyguard.CarrierText{cf99ae9 V.ED..... ......ID 56,0-462,172 #7f0a025c app:id/keyguard_carrier_text} during layout: running second layout pass
09-18 20:34:20.289  3093  3093 E i2c_geni 88c000.i2c: i2c error :-107
09-18 20:34:23.412  1939  1939 E KeyguardViewMediator: mHideAnimationFinishedRunnable#run
09-18 20:34:23.476   942  2746 E audio_hw_utils: audio_extn_utils_send_app_type_cfg: Failed to derive app_type for uc type : 0x1
09-18 20:34:23.476   942  2746 E ACDB-LOADER: Error: ACDB AudProc vol returned = -19
09-18 20:34:23.500  1485  1550 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.USER_PRESENT flg=0x24200010 } to org.bromite.bromite/org.chromium.chrome.browser.sharing.click_to_call.ClickToCallMessageHandler$PhoneUnlockedReceiver
09-18 20:34:23.501  3093  3093 E i2c_geni 88c000.i2c: i2c error :-107
09-18 20:34:23.515   942  2746 E ACDB-LOADER: Error: ACDB AudProc vol returned = -19
09-18 20:34:28.078   952   952 W healthd : battery l=100 v=4388 t=26.2 h=2 st=2 c=-357500 fc=3003000 cc=301 chg=a
09-18 20:34:32.449  1485  1570 E libc    : Access denied finding property "vendor.debug.egl.changepixelformat"
09-18 20:34:32.465  1191  1444 E fpc_tac : fpc_irq_wait_reset error FPC_ERROR_CANCELLED
09-18 20:34:32.467   942  2746 E audio_hw_utils: audio_extn_utils_send_app_type_cfg: Failed to derive app_type for uc type : 0x1
09-18 20:34:32.468   942  2746 E ACDB-LOADER: Error: ACDB AudProc vol returned = -19
09-18 20:34:32.476  1485  1570 E libc    : Access denied finding property "vendor.debug.egl.swapinterval"
09-18 20:34:32.481  1485  1570 E libc    : Access denied finding property "vendor.debug.egl.swapinterval"
09-18 20:34:32.508  1485  1485 W FingerprintService: client com.android.systemui is authenticating...
09-18 20:34:32.511  1485  1570 E libc    : Access denied finding property "vendor.debug.egl.swapinterval"
09-18 20:34:32.512   942  2746 E ACDB-LOADER: Error: ACDB AudProc vol returned = -19
09-18 20:34:32.529  1485  1570 E libc    : Access denied finding property "vendor.debug.egl.swapinterval"
09-18 20:34:32.578  1485  1570 E libc    : Access denied finding property "vendor.debug.egl.swapinterval"
09-18 20:34:32.594  1485  1570 E libc    : Access denied finding property "vendor.debug.egl.swapinterval"
09-18 20:34:32.879  1485  1570 E libc    : Access denied finding property "vendor.debug.egl.swapinterval"
09-18 20:34:32.897  1485  1570 E libc    : Access denied finding property "vendor.debug.egl.swapinterval"
09-18 20:34:32.914  1485  1570 E libc    : Access denied finding property "vendor.debug.egl.swapinterval"
09-18 20:34:33.214  1485  1890 E WifiClientModeImpl: getWifiLinkLayerStats called without an interface
09-18 20:34:33.231  1939  1939 W View    : requestLayout() improperly called by com.android.keyguard.CarrierText{cf99ae9 V.ED..... ......ID 56,0-462,172 #7f0a025c app:id/keyguard_carrier_text} during layout: running second layout pass
09-18 20:34:33.242  3093  3093 E i2c_geni 88c000.i2c: i2c error :-107
09-18 20:34:33.261  2886  2886 E libnfc_nci: [ERROR:NativeNfcTag.cpp(866)] nativeNfcTag_doDisconnect: tag already deactivated
09-18 20:34:37.956  1485  1544 W ActivityTaskManager: Sleep timeout!  Sleeping now.
```
</details>

**Comment by chirayudesai** [comment]
That might not be related to something here in apv though. Not sure.

Stupid question but can you try to connect to that address/IP?

This one time I couldn't add an eSIM to my phone, started looking at logs, it couldn't connect, turns out the ISP server was down...

**Comment by dan-v** [comment]
> Stupid question but can you try to connect to that address/IP?

lol, yeah not stupid and it definitely is not reachable for me.

**Comment by TheRingMaster** [comment]
What about whitelist support? Some perms are needed in the new ext partition no?

**Comment by chirayudesai** [comment]
This can be closed now, everything works, and this has been running fine for months!
